[package]
name = "rust_test"
version = "0.1.0"
authors = ["Natsuki Ogata <n.ogata@topcon.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
